# Generated by Django 4.2.4 on 2023-08-10 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retina', '0002_remove_patient_cf_x_remove_patient_cf_y_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='url',
            new_name='link',
        ),
    ]
