# Generated by Django 4.2.4 on 2023-09-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retina', '0004_patient_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='height',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='od_x',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='od_y',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='width',
        ),
        migrations.AddField(
            model_name='patient',
            name='dr_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_name',
            field=models.CharField(default='', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.IntegerField(default=0),
        ),
    ]
