# Generated by Django 4.2.4 on 2023-09-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retina', '0005_remove_patient_height_remove_patient_od_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='image_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default=0, max_length=100, primary_key=True, serialize=False),
        ),
    ]
