# Generated by Django 4.2.3 on 2023-09-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retina', '0007_remove_patient_image_number_patient_patient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_name',
            field=models.CharField(default='def', max_length=255),
        ),
    ]
