# Generated by Django 4.2.3 on 2023-09-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retina', '0008_alter_patient_patient_id_alter_patient_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
